### ISSUE TITLE
Weird line in GeoTIFF metadata parsing

### ISSUE THREAD

**Issue by galarlo** [fabric-io-rodrigues/GeoTiffCOG#1]
Hello,
I've noticed something weird in `GeoTiff.ParseMetadata`. I'm not sure whether it's a bug or if I missed something.
[In the following line](https://github.com/fabric-io-rodrigues/GeoTiffCOG/blob/fa0645060048a21b08cfbbbcdcd48b77a5f514de/GeoTiffCOG/GeoTiff.cs#L280)
`double pixelSizeY = BitConverter.ToDouble(modelPixelScale, 8) * -1;` 
Why is the value multiplied by `-1`?

**Comment by fabric-io-rodrigues** [comment]
Thanks for the contribution, I understand that it has already been answered in the DEM.Net thread: https://github.com/dem-net/DEM.Net/issues/96
