### ISSUE TITLE
Incorrect value being returned

### ISSUE THREAD

**Issue by JackClouseau** [fabric-io-rodrigues/GeoTiffCOG#2]
Hi,
nice work!  I have just tried to use your project with a GeoTiff file I am using for my test purposes.

I tried this:  .\GeoTiffCOGConsole.exe https://cdn.proj.org/fr_ign_ggm00v2.tif 14.5 -61
and I get an incorrect result of 0.  The correct result should be around -40 m.

I verified it against this:  
https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height-calculator.html

I think it might be something to do with the way untiled files are handled.

**Comment by fabric-io-rodrigues** [comment]
Thanks for reporting. There was a problem processing non-tiled tiff.

**Comment by JackClouseau** [comment]
Excellent.  I can confirm that this issue is now fixed!
