### ISSUE TITLE
No data at point

### ISSUE THREAD

**Issue by JackClouseau** [fabric-io-rodrigues/GeoTiffCOG#3]
Hi,

I have been doing some further testing and come across a potential problem.

I am using this file: au_ga_AUSGeoid2020_20180201.tif  with coordinates  -34.5; 133.5
The height value returned is -32768.

Do you think we should add some more conditions to this:

GetElevationAtPoint::
                <snip>
                if (heightValue > 32768)
                {
                    heightValue = metadata.NoDataValueFloat;
                }
                <snip>

such that NoDataValueFloat is returned (when the height value is -32768).

Thanks.

**Comment by fabric-io-rodrigues** [comment]
You're right, need to have the min/max range. When I have time, I'll see it. Or if you prefer, feel free to create a pull-request to add a fix!

Thank you!
